### ISSUE TITLE
py27 includes panel, but that is not part of the stdlib

### ISSUE THREAD

**Issue by pmeier** [omnilib/stdlibs#57]
```python
from stdlibs import py27

assert "panel" in py27.module_names
```

However searching in the documentation does not list [any module with that name](https://docs.python.org/2.7/search.html?q=panel). Furthermore, I also can't import it

```bash
$ conda create -y -n py27 -c conda-forge python=2.7
[...]
$ conda run -n py27 python -c 'import panel'
Traceback (most recent call last):
  File "<string>", line 1, in <module>
ImportError: No module named panel
[...]
```

I found this while trying to use `usort` on a project that uses [`panel`](https://panel.holoviz.org/) the web app framework and was kinda baffled why this was always sorted into the wrong block.

**Comment by amyreese** [comment]
So I had to dig a bit to figure it out, and this looks like the worst kind of "technically correct" moment. 😅

Python 2.x tarballs include "plat-*" libs, which are platform-specific modules that only get installed on the relevant platforms. Eg, `Lib/plat-linux2` is included in Linux runtimes, and anything in that directory is importable in the global namespace, so:

```
amethyst@nago ~ » python2
Python 2.7.18 (default, Jul 20 2023, 04:08:34)
[GCC 10.2.1 20210110] on linux2
Type "help", "copyright", "credits" or "license" for more information.
>>> import IN
>>> IN
<module 'IN' from '/home/amethyst/.pyenv/versions/2.7.18/lib/python2.7/plat-linux2/IN.pyc'>
```

And of course, if we look for something named panel:

```
(.venv) amethyst@mordin ~/workspace/stdlibs main± » find .cache/Python-2.7.18 -name 'panel.*'
.cache/Python-2.7.18/Lib/curses/panel.py
.cache/Python-2.7.18/Lib/plat-irix6/panel.py
.cache/Python-2.7.18/Lib/plat-irix5/panel.py
```

So, *technically*, `panel` was in the global stdlib for Python 2.7, but only when running on IRIX... 🫠

All that said, at this point, since µsort only supports running on source files with Python 3 syntax, we should probably make µsort only care about what's in the Python 3 stdlib.

**Comment by amyreese** [comment]
> That would work for me. Shall I send a PR?

Yes please 😊

**Comment by pmeier** [comment]
I've opened facebook/usort#266. With that and the fact that `stdlibs` is actually correct here, I'm closing this.
